server:
  applicationConnectors:
    - type: http
      port: 8090

logging:
  level: DEBUG

database:
  driverClass: org.hsqldb.jdbc.JDBCDriver
  user: sa
  password: sa
  url: jdbc:hsqldb:target/videorental
  validationQuery: "SELECT * FROM INFORMATION_SCHEMA.SYSTEM_TABLES"
